### ISSUE TITLE
Incorrect output model scale

### ISSUE THREAD

**Issue by MatousKundrik** [riccardomarin/NICP#2]
Input scan is normalized as not to exceed a size of 1 in any dimension during voxelization for LVD step. 

https://github.com/riccardomarin/NICP/blob/7c414129972886bc172512c48fe81079df1aebd8/src/lvd_templ/evaluation/utils.py#L315C1-L318C35

Resulting SMPL meshes are never scaled back up to match input scan scale.

**Comment by riccardomarin** [comment]
Hi @MatousKundrik ,
Thank you much for you feedback and sorry for the late reply.

Delivering the output in a canonical space is useful if one wants to inspect results since they are easier to render. To let the user decide, in the last commit, I introduced an option to select in which space the output should be delivered (more details can be found in the README).
I hope this can solve your use cases, and thank you again for your time.
