### ISSUE TITLE
No module named 'nncore.common'

### ISSUE THREAD

**Issue by AkhavanE** [riccardomarin/NICP#8]
Hello 
we got to this error:
ModuleNotFoundError: No module named 'nncore.common'
 by running this command:
PYTHONPATH=. python ./src/lvd_templ/evaluation/evaluation_benchmark.py

Would you please help us with this error? Where we can install nncore.common (nn_core.common)?

**Comment by riccardomarin** [comment]
Hi @AkhavanE ,
Thanks for reaching out.

`nncore` is a library that is installed along with other dependencies. You can find the reference in this file:
https://github.com/riccardomarin/NICP/blob/12e0a8047ee935dd6ab960d98c26fb48eb5e563f/setup.cfg#L18

Your error may be caused by a failure of the `pip install -e .` command, which is part of the installation script:
https://github.com/riccardomarin/NICP/blob/main/install.sh

I recommend creating a clean environment and following the `install.sh` script. 

Let me know if this solves your issue!
